name: "Assign pr-bot"
on:
  pull_request:
    types: [opened,ready_for_review]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: "Request review from pr-bot"
      uses: rowi1de/auto-assign-review-teams@v.1.1.0
      with:
        repo-token: ${{ secrets.REPO_TOKEN }}
        persons: "pr-bot"
        include-draft: false
